fontist/fontist

.github/workflows/ubuntu.yml, .travis.yml, README.md, bin/setup, fontist.gemspec
This commit adds the GitHub actions setup to build and run our suite on ubuntu for now. Currently, it only usages one single ruby version to run our test suite.
As soon as the gem is ready then let's also adds other platforms and also add multiple ruby version so we can be sure it's stable in our expected eco-system.
=> Add GitHub action setup for ubuntu

.github/workflows/ubuntu.yml, .gitignore, README.md, assets/source.yml, fontist.gemspec, lib/fontist.rb, lib/fontist/data/sources.yml, lib/fontist/downloader.rb, lib/fontist/finder.rb, lib/fontist/ms_vista_font.rb, lib/fontist/source.rb, lib/fontist/system_font.rb, spec/fontist/downloader_spec.rb, spec/fontist/finder_spec.rb, spec/fontist/ms_vista_font_spec.rb, spec/fontist/source_spec.rb, spec/fontist/system_font_spec.rb, spec/spec_helper.rb
This commit adds an interface that will allow us to find a font in the user's system. Or even better, if the font is not within user's system but one of our supported font then it will download the font and return the fonts path to the user. Usages:
```ruby
Fontist::Finder.find("CALIBRI.TTF")
```
=> Add an interface to find or download a font

bin/console, lib/fontist/ms_vista_font.rb, lib/fontist/system_font.rb, spec/fontist/finder_spec.rb
Currently, the font lookup is case sensitive, and it also does not use any of the caches. So, this commit changes this and it will try use the case insensitive version for font lookup.
This also usages the cache unless we explicitly specify to download the file again. And, the font lookup also includes the `assets` directory, this will also be used when finding a font.
=> Adjust font lookup and downloading

lib/fontist.rb, lib/fontist/errors.rb, lib/fontist/finder.rb, spec/fontist/finder_spec.rb
Currently, the finder interface is doing the job for font lookup and also to download the fonts if missing. But, in reality we need user to accept the font terms, so this commit changes this and it will raise an error for installable fonts instead of downloading it directly.
Later, we will also add suggestion for user on how to download those font from the supported libraries.
=> Do not download the font through finder

assets/source.yml, lib/fontist.rb, lib/fontist/errors.rb, lib/fontist/finder.rb, lib/fontist/installer.rb, lib/fontist/ms_vista_font.rb, lib/fontist/system_font.rb, spec/fontist/finder_spec.rb, spec/fontist/installer_spec.rb, spec/fontist/ms_vista_font_spec.rb, spec/fontist/system_font_spec.rb
For uninstalled font we want to allow user to download those with proper permission. This commit adds those necessary changes, so now user have a way to utilize `fontist` to download any of the supported fonts. This interface will also return the downloaded paths, so the user can decide what to do with that.
=> Add installer to download supported font

.github/workflows/windows.yml, assets/source.yml, lib/fontist.rb, lib/fontist/ms_vista_font.rb, spec/fontist/finder_spec.rb, spec/fontist/installer_spec.rb
This commit adds the github action setup to run the test suite in windows. This commit also adds the correct path for windows font lookup.
Since, all of these fonts are already available in widows so we also skipped the download process for that. But if there are some edge cases then we will also need to take care of those in the future.
=> Add action to run test suite in windows

.github/workflows/macosx.yml, assets/source.yml
This commit changes the paths for mac osx font lookup, and this also adds the github action setup to run our test suite in the latest Mac OSX build.
Closes #9
=> Add action to run test suite in MacOSX

lib/fontist.rb, lib/fontist/system_font.rb
Currently, each gem version is maintaining a local version for the fonts, which might not be ideal when user will install multiple fontist version. This commit changes this to use a global `.fontist`
directory where it can re-used between multiple versions.
=> Add a global fonts path for fontist

fontist.gemspec, lib/fontist/data/formulas/source_font.yml, lib/fontist/data/source.yml, lib/fontist/downloader.rb, lib/fontist/errors.rb, lib/fontist/formulas.rb, lib/fontist/formulas/base.rb, lib/fontist/formulas/ms_vista.rb, lib/fontist/formulas/source_font.rb, lib/fontist/installer.rb, spec/fontist/downloader_spec.rb, spec/fontist/formulas/ms_vista_spec.rb, spec/fontist/formulas/source_font_spec.rb, spec/spec_helper.rb, spec/support/fontist_helper.rb
This commit adds the support for source font formulas, you can find supported font list `lib/fontist/data/forumlas/source**`. So, now it will download and extract source fonts if necessary.
=> Add support for source font formulas

lib/fontist/data/formulas/ms_system.yml, lib/fontist/data/source.yml, lib/fontist/downloader.rb, lib/fontist/formulas.rb, lib/fontist/formulas/ms_system.rb, lib/fontist/installer.rb, spec/fontist/formulas/ms_system_spec.rb
This commit adds the support for Microsfot's true type fonts, and this includes `Arial`, `Times`, `Verdana` and the `trebuc`. We do not have support for font styles yet, so looking for the `Times` will return all available font's for that style.
=> Add support for microsoft's true types

lib/fontist/data/formulas/courier.yml, lib/fontist/data/source.yml, lib/fontist/formulas.rb, lib/fontist/formulas/base.rb, lib/fontist/formulas/courier_font.rb, spec/fontist/formulas/courier_font_spec.rb
This commit adds support for the courier fonts, so now user can look for any of the courier fonts and also download those when necessary. This commit also extract out some behavior so that could be helpful for the future approach for formulas.
=> Add support for the courier fonts

lib/fontist/data/formulas/source_font.yml, lib/fontist/formulas/base.rb, lib/fontist/formulas/courier_font.rb, lib/fontist/formulas/helpers/exe_extractor.rb, lib/fontist/formulas/helpers/zip_extractor.rb, lib/fontist/formulas/ms_system.rb, lib/fontist/formulas/ms_vista.rb, lib/fontist/formulas/source_font.rb
Earlier, we were using zip extraction & everything else on the source font itself. But now that we started implementing a new formula structure, so this commit migrates the zip extractions
to a separate concern, so it's only one place where we'll need to change in the future.
This also extract out some non common behaviors, like: Exe, or Zip extraction to separate helper module, so now each formula doesn't need to include everything but only pick the one they need for them.
=> Adopt new structure for source fonts

lib/fontist.rb, lib/fontist/data/formulas/courier.yml, lib/fontist/data/formulas/ms_system.yml, lib/fontist/data/formulas/ms_vista.yml, lib/fontist/data/formulas/source_font.yml, lib/fontist/finder.rb, lib/fontist/formula_finder.rb, lib/fontist/installer.rb, spec/fontist/finder_spec.rb, spec/fontist/formula_finder_spec.rb, spec/fontist/installer_spec.rb, spec/fontist/source_spec.rb
As of now, we are doing hard lookup for fonts by their exact name and also there are no way to specify font meta data like human readable name or different styles.
But in the long term plan - moving forward with font formulas we need to specify font style as well. So, this commit adds those necessary changes so we can specify font name, and the styles for font. This also adopt this changes for the lookup
=> Add support for meta data for fonts

lib/fontist/formula_finder.rb, lib/fontist/formulas/base.rb, lib/fontist/system_font.rb, spec/fontist/formula_finder_spec.rb, spec/fontist/formulas/courier_font_spec.rb, spec/fontist/system_font_spec.rb
Previously, we were only using the direct font name for lookup and installation, so it was pretty straight forward. But, now that font lookup/installation using font meta data like, name so this commit adopt those changes.
This changes the system font interface and as well as the base formula interface, so the library should work as expected.
=> Adopt font lookup for font meta data

lib/fontist/formula_finder.rb, lib/fontist/formulas.rb, lib/fontist/formulas/cleartype_fonts.rb, lib/fontist/formulas/font_formula.rb, lib/fontist/formulas/helpers/dsl.rb, lib/fontist/formulas/helpers/exe_extractor.rb, lib/fontist/installer.rb, lib/fontist/registry.rb, spec/fontist/formula_finder_spec.rb, spec/fontist/formulas/cleartype_fonts_spec.rb, spec/fontist/formulas/courier_font_spec.rb, spec/fontist/formulas_spec.rb, spec/fontist/installer_spec.rb
Long term plan with `fontist` is to allow anyone to add custom font definition using a pre-specified structure, where anyone can add new fonts by following a custom fontist DSL.
This commit is the initial step into that direction, this defines a custom DSL handler, where it will allow user to define the font resources and also how to extract these fonts from any specified resources.
=> Add support for formulas with A DSL

lib/fontist.rb, lib/fontist/downloader.rb, lib/fontist/formulas.rb, lib/fontist/formulas/font_formula.rb, lib/fontist/formulas/helpers/dsl.rb, lib/fontist/formulas/helpers/zip_extractor.rb, lib/fontist/formulas/open_sans_fonts.rb, spec/fontist/downloader_spec.rb, spec/fontist/formulas/open_sans_fonts_spec.rb
This commit adds the OpenSans font formula, so now user should be able to use this with the fontist downloader. This will provide the following list of fonts.
```
OpenSans-Bold.ttf
OpenSans-BoldItalic.ttf
OpenSans-ExtraBold.ttf
OpenSans-ExtraBoldItalic.ttf
OpenSans-Italic.ttf
OpenSans-Light.ttf
OpenSans-LightItalic.ttf
OpenSans-Regular.ttf
OpenSans-Semibold.ttf
OpenSans-SemiboldItalic.ttf
```
=> Add the OpenSans font formula

lib/fontist/formulas.rb, lib/fontist/formulas/euphemia_font.rb, lib/fontist/formulas/font_formula.rb, lib/fontist/formulas/helpers/dsl.rb, spec/fontist/formulas/euphemia_font_spec.rb
This commit imports the font formula for Euphemia Font form the formulas repository and also adds minor adjustment to the extract method. This formula will provide the following fonts:
```
Euphemia UCAS Bold 2.6.6.ttf
Euphemia UCAS Italic 2.6.6.ttf
Euphemia UCAS Regular 2.6.6.ttf
```
=> Add font formula for Euphemia Font

lib/fontist/formulas.rb, lib/fontist/formulas/helpers/zip_extractor.rb, lib/fontist/formulas/montserrat_font.rb, spec/fontist/formulas/montserrat_font_spec.rb
This commit imports the `montserrat` formula from the formulas repository. It also added a minor adjustment and also disables the sha verification for this formula. This formulas provides the following fonts:
```
Montserrat-Black.otf
Montserrat-BlackItalic.otf
Montserrat-Bold.otf
Montserrat-BoldItalic.otf
Montserrat-ExtraBold.otf
Montserrat-ExtraBoldItalic.otf
Montserrat-ExtraLight.otf
Montserrat-ExtraLightItalic.otf
Montserrat-Italic.otf
Montserrat-Light.otf
Montserrat-LightItalic.otf
Montserrat-Medium.otf
Montserrat-MediumItalic.otf
Montserrat-Regular.otf
Montserrat-SemiBold.otf
Montserrat-SemiBoldItalic.otf
Montserrat-Thin.otf
Montserrat-ThinItalic.otf
MontserratAlternates-Black.otf
MontserratAlternates-BlackItalic.otf
MontserratAlternates-Bold.otf
MontserratAlternates-BoldItalic.otf …
```
=> Add font formula for montserrat fonts

lib/fontist/formulas.rb, lib/fontist/formulas/helpers/zip_extractor.rb, lib/fontist/formulas/overpass_font.rb, spec/fontist/formulas/overpass_font_spec.rb
This commit imports the overpass formula from fontist formula repository. This modify the extract method a bit so it can look into the sub directories. This formula can be used to install the following list of fonts:
```
overpass-bold-italic.otf
overpass-bold.otf
overpass-extrabold-italic.otf
overpass-extrabold.otf
overpass-extralight-italic.otf
overpass-extralight.otf
overpass-heavy-italic.otf
overpass-heavy.otf
overpass-italic.otf
overpass-light-italic.otf
overpass-light.otf
overpass-mono-bold.otf
overpass-mono-light.otf
overpass-mono-regular.otf
overpass-mono-semibold.otf
overpass-regular.otf
overpass-semibold-italic.otf
overpass-semibold.otf
overpass-thin-italic.otf
overpass-thin.otf
```
=> Add font formulas for overpass fonts

lib/fontist/formulas.rb, lib/fontist/formulas/source_fonts.rb, spec/fontist/formulas/euphemia_font_spec.rb, spec/fontist/formulas/montserrat_font_spec.rb, spec/fontist/formulas/open_sans_fonts_spec.rb, spec/fontist/formulas/source_fonts_spec.rb
This commit imports the source fonts formula from the fontist formula repository. This also adds a minor adjustment for the fonts sud-directory for zip extractions. On installation this fonts will provides the following fonts with all styles:
```
Source Code Pro
Source Sans Pro
Source Serif Pro
```
=> Add a formulas for the source fonts

lib/fontist/formulas.rb, lib/fontist/formulas/stix_fonts.rb, spec/fontist/formulas/stix_fonts_spec.rb
This commit imports the stix_fonts formula form the fontist formula repository. This also changes the zip extraction to look into the nested sub directories for fonts. Installation for this formula will provide the following fonts:
```
STIX2Math.otf
STIX2Text-Bold.otf
STIX2Text-BoldItalic.otf
STIX2Text-Italic.otf
STIX2Text-Regular.otf
```
=> Add support for stix fonts formula

lib/fontist/formulas.rb, lib/fontist/formulas/tahoma_font.rb, spec/fontist/formulas/tahoma_font_spec.rb
This commit imports the tahoma font formula from the fontist formula repository. After installation this formula will add the following fonts:
```
tahoma.ttf
```
=> Add support for the tahoma formula

lib/fontist/formulas.rb, lib/fontist/formulas/georgia_font.rb, spec/fontist/formulas/georgia_font_spec.rb
This commit adds the support for Georgia font formula, this is also another extraction from the MS true type formula. So, now we can use `fontist` to install Georgia fonts. This includes:
```
Georgia.TTF
Georgiab.TTF
Georgiai.TTF
Georgiaz.TTF
```
=> Add support for Georgia fonmula

lib/fontist/formulas.rb, lib/fontist/formulas/impact_font.rb, spec/fontist/formulas/impact_font_spec.rb
This commit adds the support for Impact formula. This is another extraction from the MS True type formula. This formula will allow fontist to install `Impact.ttf` font.
=> Add support for Impact font formula

lib/fontist/formulas.rb, lib/fontist/formulas/webding_font.rb, spec/fontist/formulas/webding_font_spec.rb
This commit adds support for `webding` fonts formula. This is also another type of MS True Type font. Now, this will allow fontist to install `Webdings.ttf` to the user system.
=> Add support for webdings formula

README.md, lib/fontist.rb, lib/fontist/font.rb, spec/fontist/font_spec.rb, spec/fontist/formulas/andale_font_spec.rb, spec/fontist/formulas/arial_black_font_spec.rb, spec/fontist/formulas/comic_font_spec.rb, spec/fontist/formulas/courier_font_spec.rb, spec/fontist/formulas/euphemia_font_spec.rb, spec/fontist/formulas/georgia_font_spec.rb, spec/fontist/formulas/impact_font_spec.rb, spec/fontist/formulas/montserrat_font_spec.rb, spec/fontist/formulas/ms_truetype_fonts_spec.rb, spec/fontist/formulas/open_sans_fonts_spec.rb, spec/fontist/formulas/overpass_font_spec.rb, spec/fontist/formulas/source_fonts_spec.rb, spec/fontist/formulas/stix_fonts_spec.rb, spec/fontist/formulas/tahoma_font_spec.rb, spec/fontist/formulas/webding_font_spec.rb
Currently, we have a `Fontist::Finder` interface to find a font, which is little bit verbose as it doesn't exactly tell what is it gonna find, a font or a formula?
This commit changes this interface to `Fontist::Font`, so now users can be sure what they are dealing with. This also adds the benefits of having a `install` or `list` interface in future.
=> Simplify the font finding interface

spec/fontist/font_formula_spec.rb
The `FontFormua` in a critical interface for additional formulas to utilize `fontist` specific DSL. This commit adds some necessary tests to ensure the basic requirements are being met.
=> Add tests for the base font formula

README.md, lib/fontist.rb, lib/fontist/font.rb, lib/fontist/font_formula.rb, lib/fontist/formula.rb, lib/fontist/system_font.rb, spec/fontist/formula_spec.rb
This commit tries to clean up the `Formula` interface. This is more of an internal interface that is being used by fontist, but this commit adds some documentation as well so developer can use this one if necessary.
=> Cleanup the formula related interface

.gitignore, lib/fontist.rb, spec/fontist/font_spec.rb, spec/fontist/formulas/andale_font_spec.rb, spec/fontist/formulas/arial_black_font_spec.rb, spec/fontist/formulas/comic_font_spec.rb, spec/fontist/formulas/courier_font_spec.rb, spec/fontist/formulas/euphemia_font_spec.rb, spec/fontist/formulas/georgia_font_spec.rb, spec/fontist/formulas/impact_font_spec.rb, spec/fontist/formulas/montserrat_font_spec.rb, spec/fontist/formulas/ms_truetype_fonts_spec.rb, spec/fontist/formulas/open_sans_fonts_spec.rb, spec/fontist/formulas/overpass_font_spec.rb, spec/fontist/formulas/source_fonts_spec.rb, spec/fontist/formulas/stix_fonts_spec.rb, spec/fontist/formulas/tahoma_font_spec.rb, spec/fontist/formulas/webding_font_spec.rb, spec/support/fontist_helper.rb
Since we've created the `~/.fontist` global directory we are not using the `assets/fonts` folder anymore. But there are some tests that are still using the folder for temporary assets.
This commit removes this folder structure and updates the tests to use the fixtures folder for the temporary test-related files
=> Remove unused temporary asset path

.github/workflows/macosx.yml, .github/workflows/ubuntu.yml, spec/fontist/downloader_spec.rb, spec/fontist/formulas/andale_font_spec.rb, spec/fontist/formulas/arial_black_font_spec.rb, spec/fontist/formulas/cleartype_fonts_spec.rb, spec/fontist/formulas/comic_font_spec.rb, spec/fontist/formulas/courier_font_spec.rb, spec/fontist/formulas/georgia_font_spec.rb, spec/fontist/formulas/impact_font_spec.rb, spec/fontist/formulas/montserrat_font_spec.rb, spec/fontist/formulas/open_sans_fonts_spec.rb, spec/fontist/formulas/source_fonts_spec.rb, spec/fontist/formulas/tahoma_font_spec.rb, spec/fontist/formulas/webding_font_spec.rb, spec/fontist/system_font_spec.rb, spec/spec_helper.rb
There are a couple of tests that runs super slow, which mainly depends on the host for those formulas. So, unless we did any
changes on those formulas we don't necessarily break those
This commit adds a mechanism by adding a rspec tag `slow_test`, so by default `bin/rspec` will ignore those slow tests. But it
will running the same as before in the CI environment.
=> Skip option for slow test locally

README.md, lib/fontist/font.rb, spec/fontist/font_spec.rb
This commit adds an interface to the `Fontist::Font` interface that will allow a user to list out all of the supported fonts.
The interface doesn't need any parameter, and you can simply do the following to list fonts:
```ruby
Fontist::Font.all
```
=> Add support to list all available fonts

lib/fontist.rb, lib/fontist/formulas.rb
The dynamic font formulas loading was not working as expected, it was mainly because of the relative paths we were using to require those files. This commit changes this to absolute paths, and also move the dynamic loading to `fontist.rb` file.
=> Fix loading issue for font formulas

lib/fontist/downloader.rb, lib/fontist/errors.rb, lib/fontist/font_formula.rb, lib/fontist/formulas/cleartype_fonts.rb, lib/fontist/formulas/ms_truetype_fonts.rb
Currently, we are selecting the first URL to download any of the source files, but that might some cause some issues sometimes. So, this commit changes this to take a random one from the list and it should not always send the traffic to one source.
=> Add randomization to select a file URL

README.md, lib/fontist/font.rb, lib/fontist/formula.rb, spec/fontist/formula_spec.rb
The `Fontist::Formula.find` method returns a list of formulas, but in reality, it's always one or should be one formula that is
expected from this interface. So this commit changes this and it also adjusts the font installer to adopt these changes.
=> Fix return type for formula finder

lib/fontist/downloader.rb, lib/fontist/formulas/cleartype_fonts.rb
This commit adds new resource URL's for the clear type fonts, This commit also extends the existing SHA verification, so now
we can also pass an array for the checksum, so it will use the list for verifications.
closes #64
=> Add new URLs for clear type formula

lib/fontist/font.rb, lib/fontist/system_font.rb
The fontist gem requires the `~/.fontist` directory to function properly. Earlier, we are checking this one in system font check
but we actually might need that for font lookup or installation so this commit moves this login to `Fontist::Font` interface, so
any call to this interface will create those missing directories
=> Ensure fontist related paths are presents

lib/fontist/system_font.rb, spec/fontist/system_font_spec.rb
The system font finder was returning the whole list of fonts for some cases like `Calib`, turns out it was a validation check for the font names, it returns empty array & that's what was causing this issue.
This commit fixes this issue, and also adds a small check for this so now we only return the matched list of fonts.
=> Fix system font finder related issues

lib/fontist/formulas/tahoma_font.rb
This commit updates the Tahoma font formula to the latest version, this version includes some differences for extraction, so it also adopts these changes. Another important thing, now we also support the Bold style for this font.
Fixes #51
=> Update tahoma formula to latest version

lib/fontist/errors.rb, lib/fontist/utils/downloader.rb
There are some formulas that might be super slow sometime, and that leaves the user with a feeling of stalling, so this commit adds a time caps to each slow download, by default it's 20 seconds and if the download is done then it closes that request.
Fair warning, the `Timeout` module doesn't have a very good reputation but for our use cases this seems to work for now, but we really should keep an eye on it for future improvement.
Fixes #96
Link: https://github.com/ankane/the-ultimate-guide-to-ruby-timeouts
=> Add a time limit for the slow formulas

lib/fontist/errors.rb, lib/fontist/utils/downloader.rb, spec/fontist/utils/downloader_spec.rb
This commit fixes the type for the Tampered error class, and it also updates the necessary downloader and their specs to adopt these changes.
Fixes #99
=> Fix type for the Tampered error class

lib/fontist/system.yml, lib/fontist/system_font.rb
This commit updates the default font lookup paths for the Mac OS, this also adds some normalization to replace username
variable with the correct system user's name.
Related #95
=> Adjust default font lookup paths

fontist.gemspec, lib/fontist.rb, lib/fontist/font.rb, lib/fontist/registry.rb, lib/fontist/utils.rb, lib/fontist/utils/downloader.rb, lib/fontist/utils/ui.rb, spec/fontist/font_spec.rb
Earlier, Fontist wasn't handling the proprietary license itself, but relying on the dependent client library to handle it for us.
But we've decided to handle the required license by fontist, so this commit adds the support for that.
There are a couple of scenarios: first of all, the open fonts, and in those case fontist won't prompt the license agreement and it will install the font from the correct formula.
The second scenario, proprietary font with required license, and in this case fontist will display the license and ask the user to
provide their confirmation, and if it is the same as the required one then it will proceed or raise an error.
Fair warning: this might cause some issue if someone tries to use fontist for some automation, where they don't provide the
correct license, but …
=> Add support for license agreement handling

.gitignore, .rubocop.yml, fontist.gemspec, lib/fontist.rb, lib/fontist/fontist_font.rb, lib/fontist/formula.rb, lib/fontist/formula_template.rb, lib/fontist/system_font.rb, spec/fixtures/system.yml, spec/fontist/cli_spec.rb, spec/fontist/font_spec.rb, spec/fontist/formula_spec.rb, spec/fontist/formulas/cleartype_font_spec.rb, spec/fontist/formulas/source_font_spec.rb, spec/fontist/formulas/stix_fonts_spec.rb, spec/fontist/system_font_spec.rb, spec/support/fontist_helper.rb
- Fix installation of "Source Hans Sans" not returning the *.ttc paths
- Fix installation of "Source" skipping and returning the wrong system fonts
- Prefer exact match by key over partial match in fonts: for "Source" return Source formula, instead of Source Code Pro formula
- Fix not working removal of whole formula
- Correct name for Source Han Sans (see https://github.com/fontist/formulas/pull/32)
=> Fix Han Sans installation

.github/workflows/release.yml, README.md, fontist.gemspec
Seems it uses a different version of bundler:
```
Run bundle install --jobs 4 --retry 3
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
In Gemfile:
bundler (~> 2.0)
Current Bundler version:
bundler (1.17.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
Could not find gem 'bundler (~> 2.0)' in any of the relevant sources:
the local ruby installation
```
https://github.com/fontist/fontist/runs/1585158834?check_suite_focus=true
=> GHA release fix

lib/fontist.rb, lib/fontist/cli.rb, lib/fontist/cli/class_options.rb, lib/fontist/google_cli.rb, lib/fontist/import/helpers/system_helper.rb, lib/fontist/import_cli.rb, lib/fontist/repo_cli.rb, lib/fontist/utils/ui.rb, spec/fontist/utils/ui_spec.rb
This PR turns off all logging for Ruby calls, but keeps for CLI.
Also adds the `--quiet` option to disable logs even in CLI.
Closes #276
=> Logging levels

README.adoc, lib/fontist/formula.rb, lib/fontist/system_index.rb, spec/fontist/formula_spec.rb, spec/fontist/system_index_spec.rb, spec/support/fontist_helper.rb
- fontist/fontist-formulas-private#8
Related PRs:
- https://github.com/metanorma/fontist-formulas-private/pull/10
Related issues:
- https://github.com/metanorma/metanorma-bsi/issues/212
Now `bundle exec ruby exe/fontist install "Frutiger" --preferred-family` don't download assets each time and produce:
```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Fonts found at:
- /Users/camobap/.fontist/fonts/Frutiger-Black.otf (from private/metanorma/frutiger formula)
- /Users/camobap/.fontist/fonts/Frutiger-BlackCn.otf (from private/metanorma/frutiger formula)
- /Users/camobap/.fontist/fonts/Frutiger-BlackItalic.otf (from private/metanorma/frutiger formula)
- …
```
=>  allow 'override' font metadata to install/query fonts

README.adoc, lib/fontist/cli.rb, lib/fontist/errors.rb, lib/fontist/font_installer.rb, lib/fontist/formula.rb, lib/fontist/formula_picker.rb, spec/examples/formulas/tex_gyre_chorus_min_fontist_1.yml, spec/examples/formulas/tex_gyre_chorus_min_fontist_and_font.yml, spec/fontist/cli_spec.rb, spec/fontist/font_spec.rb
This PR lets define a requirement in a formula for minimum fontist version. So instead of failing fontist would tell it needs an upgrade.
In continuation of https://github.com/fontist/formulas/pull/150
=> Check for required fontist version in formulas

lib/fontist/import/google.rb, lib/fontist/import/google/new_fonts_fetcher.rb, lib/fontist/import/google_import.rb, lib/fontist/import_cli.rb
After that PR the import would fetch by 100 formulas per time. It's easier to debug it that way later.
See https://github.com/fontist/formulas/pull/142
=> The limit option when importing formulas for Google Fonts

fontist.gemspec
This is to ensure that `coradoc` can be installed side by side, as `coradoc` requires a feature only present since thor 1.3.0
Ref: metanorma/coradoc#128
=> gemspec: Untighten version of thor
