- lib/fontist/formulas/base.rb
- lib/fontist/formulas/ms_system.rb
- lib/fontist/formulas/ms_vista.rb
- spec/fontist/formulas/ms_system_spec.rb
- spec/fontist/formulas/ms_vista_spec.rb
Recently, we introduced some block based extraction to hide out some internal details. This commit changes the existing code to comply with those changes. Next, would be add more source and then open it up as font formula.
> Refactor existing code to use extractor

- .github/workflows/check_google.yml
- README.md
- bin/check_google
- lib/fontist/import/google.rb
- lib/fontist/import/google/fonts_public.md
- lib/fontist/import/google/fonts_public.txt
- lib/fontist/import/google/new_fonts_fetcher.rb
- lib/fontist/import/google_check.rb
- lib/fontist/import/google_import.rb
- lib/fontist/import/otf_parser.rb
- lib/fontist/import/otf_style.rb
> Check for new Google fonts

- bin/convert_formulas
- lib/fontist/import/convert_formulas.rb
- lib/fontist/import/formula_serializer.rb
> Script for converting formulas from Ruby to YAML

- .gitignore
- README.md
- fontist.gemspec
- lib/fontist.rb
- lib/fontist/formulas.rb
- lib/fontist/import/google/new_fonts_fetcher.rb
- lib/fontist/utils.rb
- lib/fontist/utils/git_requirement.rb
- spec/support/load_formulas_helper.rb
> Extract formulas

- bin/fontist
- fontist.gemspec
- lib/fontist/cli.rb
- lib/fontist/formulas.rb
- spec/support/load_formulas_helper.rb
> Update formulas with `fontist update`

- fontist.gemspec
- lib/fontist/cli.rb
- lib/fontist/font_formula.rb
- lib/fontist/formulas.rb
- lib/fontist/import/create_formula.rb
- lib/fontist/import/extractors.rb
- lib/fontist/import/extractors/extractor.rb
- lib/fontist/import/extractors/msi_extractor.rb
- lib/fontist/import/extractors/zip_extractor.rb
- lib/fontist/import/formula_builder.rb
- lib/fontist/import/text_helper.rb
- lib/fontist/utils.rb
- lib/fontist/utils/downloader.rb
- lib/fontist/utils/exe_extractor.rb
- lib/fontist/utils/msi_extractor.rb
See #127 
Formula's data is here https://github.com/fontist/formulas/pull/8
Generated with:
```sh
bin/fontist create-formula --name "Adobe Reader 19" --mirror https://web.archive.org/web/20200816153035/http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/misc/FontPack1902120058_XtdAlf_Lang_DC.msi http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/misc/FontPack1902120058_XtdAlf_Lang_DC.msi
```
> Support extraction from MSI (OLE)

- fontist.gemspec
- lib/fontist/font_formula.rb
- lib/fontist/import/create_formula.rb
- lib/fontist/import/extractors.rb
- lib/fontist/import/extractors/seven_zip_extractor.rb
- lib/fontist/utils.rb
- lib/fontist/utils/seven_zip_extractor.rb
See #128 
Formula's data is here https://github.com/fontist/formulas/pull/30
Generated with:
```sh
bin/fontist create-formula --name "Adobe Reader 20" --mirror https://web.archive.org/web/20200816153003/http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2001220041/AcroRdrDC2001220041_en_US.exe http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2001220041/AcroRdrDC2001220041_en_US.exe
```
> Support extraction from exe (7z)

- spec/examples/formulas/adobe_reader_19.yml
- spec/examples/formulas/adobe_reader_20.yml
- spec/fontist/font_spec.rb
- spec/fontist/import/create_formula_spec.rb
> Specs for installation with msi and 7z

- bin/fontist
- lib/fontist.rb
- lib/fontist/cli.rb
- lib/fontist/font_formula.rb
- lib/fontist/formula.rb
- lib/fontist/formula_template.rb
- lib/fontist/utils/downloader.rb
- lib/fontist/utils/exe_extractor.rb
- lib/fontist/utils/ui.rb
- spec/fontist/cli_spec.rb
- spec/fontist/font_spec.rb
- spec/support/avoid_printing.rb
- spec/support/fontist_helper.rb
> CLI `install`

- bin/fontist
- lib/fontist.rb
- lib/fontist/cli.rb
- lib/fontist/font.rb
- lib/fontist/fontist_font.rb
- lib/fontist/utils/cache.rb
- lib/fontist/utils/downloader.rb
- spec/fontist/font_spec.rb
- spec/support/fontist_helper.rb
> CLI uninstall

- lib/fontist/cli.rb
- lib/fontist/font.rb
- spec/fontist/cli_spec.rb
- spec/fontist/font_spec.rb
- spec/support/fontist_helper.rb
> CLI status

- lib/fontist/system_font.rb
- lib/fontist/utils.rb
- lib/fontist/utils/system.rb
- spec/fontist/font_spec.rb
- spec/spec_helper.rb
> System fonts (MacOS, Windows)

- README.md
- lib/fontist.rb
- lib/fontist/cli.rb
- lib/fontist/errors.rb
- lib/fontist/formula.rb
- lib/fontist/locations.rb
- lib/fontist/system_font.rb
- spec/fontist/cli_spec.rb
- spec/support/fontist_helper.rb
- spec/support/yaml_matcher.rb
> Manifest: get fonts locations

- lib/fontist/cli.rb
- lib/fontist/font.rb
- lib/fontist/formula_template.rb
- lib/fontist/import/formula_builder.rb
- lib/fontist/import/helpers/system_helper.rb
- spec/fontist/font_spec.rb
- spec/fontist/import/create_formula_spec.rb
Helpful at least for testing new formulas.
> CLI install with force flag

- lib/fontist/formula_template.rb
- lib/fontist/import/formula_builder.rb
- lib/fontist/import/helpers/system_helper.rb
- spec/fontist/import/create_formula_spec.rb
- Fixes failing specs after new formulas added (could not load formulas with collection fonts only)
- Checks mirrors during formula creation
> New formulas

- lib/fontist/cli.rb
- lib/fontist/import/create_formula.rb
- lib/fontist/import/otf/font_file.rb
- lib/fontist/import/recursive_extraction.rb
- lib/fontist/utils/cache.rb
- lib/fontist/utils/exe_extractor.rb
- spec/examples/formulas/guttman.yml
- spec/fontist/font_spec.rb
- spec/fontist/import/create_formula_spec.rb
Support of langpack archives
See fontist/formulas#18, fontist/formulas#17, etc
> Subarchive option

- lib/fontist/cli.rb
- lib/fontist/font.rb
- lib/fontist/font_formula.rb
- lib/fontist/utils/cache.rb
- lib/fontist/utils/downloader.rb
- lib/fontist/utils/exe_extractor.rb
- lib/fontist/utils/ui.rb
- lib/fontist/utils/zip_extractor.rb
- spec/fontist/cli_spec.rb
- spec/fontist/font_spec.rb
- spec/support/avoid_printing.rb
> Download progress

- lib/fontist/cli.rb
- lib/fontist/errors.rb
- lib/fontist/font_formula.rb
- lib/fontist/formula_template.rb
- lib/fontist/import/create_formula.rb
- lib/fontist/import/files/collection_file.rb
- lib/fontist/import/files/file_requirement.rb
- lib/fontist/import/files/font_detector.rb
- lib/fontist/import/formula_builder.rb
- lib/fontist/import/otf/font_file.rb
- lib/fontist/import/recursive_extraction.rb
- lib/fontist/utils/dsl.rb
- lib/fontist/utils/dsl/font.rb
- lib/fontist/utils/exe_extractor.rb
- lib/fontist/utils/zip_extractor.rb
- spec/examples/formulas/adobe_reader_19.yml
- spec/examples/formulas/guttman.yml
- spec/examples/formulas/korean.yml
- spec/fontist/font_spec.rb
- spec/fontist/import/create_formula_spec.rb
Closes fontist/formulas#53
See also fontist/formulas#55
> Autodetect font files

- lib/fontist/cli.rb
- lib/fontist/import/create_formula.rb
- lib/fontist/import/files/font_detector.rb
- lib/fontist/import/formula_builder.rb
- lib/fontist/import/recursive_extraction.rb
- lib/fontist/utils/zip_extractor.rb
- spec/examples/formulas/work_sans.yml
- spec/fontist/font_spec.rb
- spec/fontist/import/create_formula_spec.rb
Closes #170 
See also fontist/formulas#56
> Subdir detection

- README.md
- lib/fontist/cli.rb
> README after the "accurate find" PR

- README.md
- lib/fontist.rb
- spec/fontist/font_spec.rb
- spec/support/fontist_helper.rb
> Environment variable to change fontist path

- README.md
- lib/fontist/cli.rb
- lib/fontist/manifest/install.rb
- lib/fontist/manifest/locations.rb
- spec/fontist/manifest/install_spec.rb
- spec/fontist/manifest/locations_spec.rb
> Manifest from Ruby

- .github/workflows/release.yml
- #187
@ronaldtse could you please add `secrets.FONTIST_CI_RUBYGEMS_API_KEY`
> #187 add GHA release workflow

- lib/fontist/fontist_font.rb
- lib/fontist/formula.rb
- lib/fontist/formula_paths.rb
- lib/fontist/index.rb
- lib/fontist/registry.rb
- lib/fontist/system_font.rb
- spec/fontist/font_spec.rb
> Formula index

- bin/fontist
- lib/fontist/cli.rb
- lib/fontist/errors.rb
- lib/fontist/font.rb
- lib/fontist/manifest/install.rb
- lib/fontist/manifest/locations.rb
- spec/fontist/cli_spec.rb
- spec/fontist/manifest/install_spec.rb
- spec/fontist/manifest/locations_spec.rb
> Raise in manifest if font not found

- lib/fontist/font.rb
- spec/fontist/manifest/install_spec.rb
> Handle nil input to avoid unknown fails in tests

- lib/fontist/cli.rb
- lib/fontist/errors.rb
- lib/fontist/system_font.rb
- lib/fontist/system_index.rb
- lib/fontist/utils.rb
- lib/fontist/utils/cache.rb
- lib/fontist/utils/locking.rb
- spec/fontist/cli_spec.rb
- spec/fontist/system_index_spec.rb
- spec/support/fontist_helper.rb
> Lock writing to system index

- lib/fontist/cli.rb
- lib/fontist/errors.rb
- lib/fontist/font.rb
- lib/fontist/manifest/locations.rb
- spec/fontist/cli_spec.rb
- spec/fontist/font_spec.rb
- spec/fontist/manifest/install_spec.rb
- spec/fontist/manifest/locations_spec.rb
> Parameterized font errors

- spec/examples/formulas/webcore.yml
- spec/fontist/formula_spec.rb
- spec/fontist/import/create_formula_spec.rb
> Fix webcore example: source is changed

- .github/workflows/rspec.yml
- lib/fontist/cli.rb
- lib/fontist/font.rb
- lib/fontist/manifest/install.rb
- spec/fontist/cli_spec.rb
> License flags

- lib/fontist/font.rb
- lib/fontist/formula.rb
- spec/fontist/cli_spec.rb
- spec/fontist/font_spec.rb
> Install additional styles

- .github/workflows/rspec.yml
- fontist.gemspec
> Fix ttfunk version

- lib/fontist/utils/cache.rb
- lib/fontist/utils/downloader.rb
- spec/fontist/font_spec.rb
> Compact progress bar

- lib/fontist/cli.rb
- lib/fontist/font.rb
- lib/fontist/font_installer.rb
- lib/fontist/import/helpers/system_helper.rb
- lib/fontist/utils/downloader.rb
- spec/fontist/cli_spec.rb
- spec/fontist/font_spec.rb
- spec/fontist/import/create_formula_spec.rb
- spec/fontist/import/sil_import_spec.rb
- spec/fontist/system_font_spec.rb
- spec/fontist/system_index_spec.rb
- spec/support/fontist_helper.rb
> No progress

- lib/fontist/manifest/install.rb
- spec/fontist/manifest/install_spec.rb
> metanorma/metanorma-cli#227 Add no_progress keyword to Fontist::Manifest::Install.from_hash

- .github/workflows/rspec.yml
- fontist.gemspec
> metanorma/metanorma#170 add ruby 3.0 back to test matrix

- .rubocop.yml
- lib/fontist/formula_paths.rb
- lib/fontist/manifest/install.rb
- lib/fontist/manifest/locations.rb
- lib/fontist/system_font.rb
- spec/fontist/cli_spec.rb
- spec/fontist/system_font_spec.rb
> Paths by style

- README.md
- lib/fontist/index.rb
- lib/fontist/indexes/base_index.rb
- spec/fontist/import/create_formula_spec.rb
- spec/support/fontist_helper.rb
See fontist/ffi-libarchive-binary#2
> xar formula

- lib/fontist/system_index.rb
- spec/fontist/system_index_spec.rb
> Skip read errors from ttfunk

- .github/workflows/metanorma.yml
- README.md
- fontist.gemspec
- lib/fontist.rb
- lib/fontist/cli.rb
- lib/fontist/errors.rb
- lib/fontist/font.rb
- lib/fontist/font_installer.rb
- lib/fontist/formula.rb
- lib/fontist/index.rb
- lib/fontist/indexes/base_index.rb
- lib/fontist/repo.rb
- lib/fontist/repo_cli.rb
- lib/fontist/utils/downloader.rb
- lib/fontist/utils/locking.rb
- spec/examples/formulas/andale.yml
- spec/fontist/cli_spec.rb
- spec/fontist/font_installer_spec.rb
- spec/fontist/font_spec.rb
- spec/fontist/import/sil_import_spec.rb
- spec/fontist/index_spec.rb
- spec/fontist/indexes/font_index_spec.rb
- spec/fontist/repo_cli_spec.rb
- spec/fontist/repo_spec.rb
- spec/fontist/system_index_spec.rb
- spec/fontist/utils/downloader_spec.rb
- spec/support/fontist_helper.rb
- spec/support/load_formulas_helper.rb
> Private fonts

- README.md
- lib/fontist/cli.rb
- lib/fontist/errors.rb
- lib/fontist/formula.rb
- lib/fontist/repo.rb
- lib/fontist/repo_cli.rb
- lib/fontist/update.rb
- spec/fontist/repo_cli_spec.rb
- spec/fontist/repo_spec.rb
- spec/fontist/update_spec.rb
- spec/support/fontist_helper.rb
> Private repos updates

- README.adoc
- README.md
- exe/fontist
- fontist.gemspec
- spec/fontist/font_spec.rb
> #249 add SOCKS support + documentation to README

- .github/workflows/metanorma.yml
- lib/fontist/import/files/collection_file.rb
- lib/fontist/import/formula_builder.rb
- lib/fontist/import/otf/font_file.rb
- lib/fontist/system_index.rb
- lib/fontist/update.rb
- spec/examples/import/webcore.yml
- spec/fontist/cli_spec.rb
- spec/fontist/font_spec.rb
- spec/fontist/formula_spec.rb
- spec/fontist/import/create_formula_spec.rb
- spec/fontist/system_index_spec.rb
- spec/fontist/update_spec.rb
- spec/support/fontist_helper.rb
> Formula versioning

- .github/workflows/metanorma.yml
> Integrate metanorma

- lib/fontist/import/recursive_extraction.rb
> Better search for license

- lib/fontist/import/recursive_extraction.rb
> Courier Prime: license search

- fontist.gemspec
- lib/fontist/system_font.rb
- lib/fontist/system_index.rb
- spec/examples/manifests/mscorefonts.yml
- spec/fontist/font_spec.rb
- spec/fontist/performance_spec.rb
- spec/fontist/system_index_spec.rb
- spec/support/fontist_helper.rb
- spec/support/performance.rb
- spec/support/system_fonts.rb
> Performance

- lib/fontist/font_installer.rb
- lib/fontist/utils/downloader.rb
- spec/fontist/font_installer_spec.rb
- spec/fontist/utils/downloader_spec.rb
- spec/support/fontist_helper.rb
Closes https://github.com/fontist/formulas/issues/99
> Redownloads

- lib/fontist/repo.rb
- lib/fontist/system_font.rb
- lib/fontist/update.rb
- spec/fontist/cli_spec.rb
- spec/fontist/font_spec.rb
- spec/fontist/formula_spec.rb
- spec/fontist/indexes/filename_index_spec.rb
- spec/fontist/system_index_spec.rb
- spec/fontist/update_spec.rb
- spec/support/fontist_helper.rb
- spec/support/load_formulas_helper.rb
See https://github.com/fontist/formulas/issues/75
- Use only necessary formulas to speed up specs load (now each run loads in 1 second instead of 15 seconds previously)
- Fix updating of a repo with a main branch instead of a master one
> Public repos

- lib/fontist/font.rb
- lib/fontist/formula.rb
- spec/examples/formulas/work_sans_macos_only.yml
- spec/fontist/font_spec.rb
See https://github.com/fontist/fontist/issues/215
> Platform formulas

- .github/workflows/rspec.yml
- lib/fontist/update.rb
- spec/fontist/update_spec.rb
- spec/support/fontist_helper.rb
Closes https://github.com/fontist/fontist/issues/272
> Font not found with private repo

- Gemfile
- README.adoc
- lib/fontist.rb
- lib/fontist/update.rb
- spec/fontist/formulas_isolation_spec.rb
See https://github.com/fontist/fontist/issues/215
> macOS formulas: follow up

- .rubocop.yml
- README.adoc
- lib/fontist.rb
- lib/fontist/cli.rb
- lib/fontist/errors.rb
- lib/fontist/font.rb
- lib/fontist/formula.rb
- lib/fontist/formula_picker.rb
- lib/fontist/import/formula_builder.rb
- lib/fontist/indexes/default_family_font_index.rb
- lib/fontist/style_version.rb
- spec/examples/formulas/au.yml
- spec/examples/formulas/au_passata_oblique.yml
- spec/examples/formulas/cleartype.yml
- spec/examples/formulas/source.yml
- spec/examples/formulas/source_sans_pro.yml
- spec/examples/formulas/source_sans_pro_version_3.yml
- spec/examples/import/adobe_reader_19.yml
- spec/examples/import/adobe_reader_20.yml
- spec/examples/import/euphemia_ucas.yml
- spec/examples/import/guttman.yml
- spec/examples/import/korean.yml
- spec/examples/import/lato.yml
- spec/examples/import/marlett.yml
- spec/examples/import/source_han_sans.yml
- spec/examples/import/webcore.yml
- spec/examples/import/work_sans.yml
- spec/fontist/cli_spec.rb
- spec/fontist/font_spec.rb
- spec/fontist/import/create_formula_spec.rb
Closes https://github.com/fontist/formulas/issues/109
> Install only sufficient formula

- lib/fontist/import/google/skiplist.yml
- lib/fontist/utils/downloader.rb
- spec/fontist/utils/downloader_spec.rb
Closes https://github.com/fontist/formulas/issues/98
> STIX Two Math

- README.adoc
- lib/fontist/cli.rb
- lib/fontist/errors.rb
- lib/fontist/font.rb
- lib/fontist/formula.rb
- spec/fontist/cli_spec.rb
> Install formula

- README.adoc
See https://github.com/fontist/fontist.org/issues/4
> README: remove obsolete notes

- fontist.gemspec
- lib/fontist/utils/cache.rb
- spec/fontist/utils/downloader_spec.rb
Closes https://github.com/metanorma/bsi-brand-assets/issues/1
> Detect archive type

- .github/workflows/metanorma.yml
- lib/fontist/import/google/new_fonts_fetcher.rb
> Fix Google update

- .github/workflows/test-and-release.yml
- .gitignore
- lib/fontist/utils/ui.rb
- lib/fontist/version.rb
- spec/fontist/font_spec.rb
- spec/fontist/system_font_spec.rb
- spec/support/fontist_helper.rb
> Added Arch Linux tests and handling of fully detached terminal mode

- lib/fontist/repo.rb
> #308 checkout main branch in favor of master if exists

- .github/workflows/metanorma.yml
- .github/workflows/test-and-release.yml
- spec/examples/import/webcore.yml
- spec/fontist/import/create_formula_spec.rb
Related: https://github.com/fontist/fontist/issues/308
> Move to external test matrix

- lib/fontist/import/google.rb
- spec/fontist/utils/downloader_spec.rb
> #317 fix ruby 3.2 related issues

- README.adoc
- lib/fontist/cache_cli.rb
- lib/fontist/cli.rb
- spec/fontist/cache_cli_spec.rb
> feature: fontist cache clear #312

- lib/fontist/cache_cli.rb
- lib/fontist/system_index.rb
- lib/fontist/utils/cache.rb
- spec/fontist/cache_cli_spec.rb
> #323 fix cache clear on dir remove

- lib/fontist/repo.rb
- lib/fontist/repo_cli.rb
- spec/fontist/repo_cli_spec.rb
- #310 
@ronaldtse feel free to suggest better output format or more/other metadata to be included in the report
> feature: CLI repo info #310

- lib/fontist/formula_picker.rb
- lib/fontist/utils/cache.rb
- spec/examples/formulas/georgia.yml
- spec/fontist/font_spec.rb
- spec/fontist/formula_picker_spec.rb
> #326 don't requirest --size-limit if resource already downloaded

- README.adoc
- fontist.gemspec
- lib/fontist/font.rb
- lib/fontist/font_installer.rb
- spec/fontist/font_spec.rb
> Install only requested fonts

- lib/fontist/cli.rb
- lib/fontist/cli/class_options.rb
- lib/fontist/import/create_formula.rb
- lib/fontist/import/recursive_extraction.rb
- spec/examples/import/lato_only_italic.yml
- spec/fontist/import/create_formula_spec.rb
See https://github.com/fontist/formulas/issues/155
> Ability to exclude some files from a formula

- fontist.gemspec
- lib/fontist/import/otf/font_file.rb
See https://github.com/fontist/formulas/pull/150
> Support Ming Uni formula

- README.adoc
- lib/fontist.rb
- lib/fontist/cli.rb
- lib/fontist/config.rb
- lib/fontist/config_cli.rb
- lib/fontist/utils/downloader.rb
- spec/fontist/utils/downloader_spec.rb
Closes https://github.com/fontist/fontist/issues/325
> Add the config subcommand

- README.adoc
- lib/fontist.rb
- lib/fontist/cli.rb
- lib/fontist/cli/class_options.rb
- lib/fontist/utils/cache.rb
- spec/fontist/cli_spec.rb
Relates to https://github.com/fontist/fontist/issues/325
> Add --no-cache to CLI

- README.adoc
- lib/fontist/config.rb
- spec/examples/formulas/lato.yml
See https://github.com/fontist/formulas/pull/162
> Fix config persistence

- fontist.gemspec
See https://github.com/fontist/fontist/actions/runs/7347853185/job/20427130732
> Fix json error on Arch

- exe/fontist
- lib/fontist/cli.rb
- lib/fontist/cli/thor_ext.rb
- lib/fontist/font.rb
- lib/fontist/helpers.rb
- lib/fontist/utils/ui.rb
- spec/fontist/cli_spec.rb
- spec/fontist/utils/downloader_spec.rb
> fix: zero exit code on fontist help #355

- lib/fontist/cli/thor_ext.rb
- lib/fontist/utils/cache.rb
- spec/fontist/cli_spec.rb
> fix: frozen string prepend #388

- lib/fontist/formula.rb
> fix: system index reading fails due to YAML.load error
